"""
Prompts package.
"""

from backend.teaching.prompts.templates import (
    SYSTEM_TEACHER_INSTRUCTION,
    LESSON_PLANNING_SYSTEM_PROMPT,
    EXPLANATION_PROMPT_TEMPLATE,
    QUESTION_GENERATION_PROMPT,
    RE_EXPLANATION_MISCONCEPTION_PROMPT
)

__all__ = [
    "SYSTEM_TEACHER_INSTRUCTION",
    "LESSON_PLANNING_SYSTEM_PROMPT",
    "EXPLANATION_PROMPT_TEMPLATE",
    "QUESTION_GENERATION_PROMPT",
    "RE_EXPLANATION_MISCONCEPTION_PROMPT",
]
